Add cross-compilation to x86_64 based on the Cirrus CI job

diff --git a/.github/workflows/apple_m.yml b/.github/workflows/apple_m.yml
--- a/.github/workflows/apple_m.yml
+++ b/.github/workflows/apple_m.yml
@@ -155,3 +155,67 @@ jobs:
               exit 1
               ;;
           esac
+name: xbuild-x86_64
+on: [push, pull_request]
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
+  cancel-in-progress: true
+
+permissions:
+  contents: read # to fetch code (actions/checkout)
+
+jobs:
+  build:
+    if: "github.repository == 'OpenMathLib/OpenBLAS'"
+    runs-on: macos-14
+
+    strategy:
+      fail-fast: false
+        
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v6
+
+      - name: Print system information
+        run: |
+          if [ "$RUNNER_OS" == "macOS" ]; then
+            sysctl -a | grep machdep.cpu
+          else
+            echo "::error::$RUNNER_OS not supported"
+            exit 1
+          fi
+
+      - name: Install Dependencies
+        run: |
+          if [ "$RUNNER_OS" == "Linux" ]; then
+            sudo apt-get install -y gfortran cmake ccache libtinfo5
+          elif [ "$RUNNER_OS" == "macOS" ]; then
+            # It looks like "gfortran" isn't working correctly unless "gcc" is re-installed.
+            brew reinstall gcc
+            brew install coreutils ccache
+            brew install llvm
+          else
+            echo "::error::$RUNNER_OS not supported"
+            exit 1
+          fi
+          
+      - name: Crossbuild OpenBLAS
+        run: |
+          #export PATH=/opt/homebrew/opt/llvm/bin:$PATH
+          #export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
+          #export CPPFLAGS="-I/opt/homebrew/opt/llvm/include" 
+          export ARCHS="i386 x86_64"
+          export ARCHS_STANDARD="i386 x86_64"
+          export ARCHS_STANDARD_32_64_BIT="i386 x86_64"
+          export ARCHS_STANDARD_64_BIT=x86_64
+          export ARCHS_STANDARD_INCLUDING_64_BIT="i386 x86_64"
+          export ARCHS_UNIVERSAL_IPHONE_OS="i386 x86_64"
+          export VALID_ARCHS="i386 x86_64"
+          xcrun --sdk macosx --show-sdk-path
+          xcodebuild -version
+          export CC=/Applications/Xcode_26.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
+          export CFLAGS="-O2 -unwindlib=none -Wno-macro-redefined -isysroot /Applications/Xcode_26.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.0.sdk -arch x86_64"
+          make TARGET=CORE2 DYNAMIC_ARCH=1 NUM_THREADS=32 HOSTCC=clang NOFORTRAN=1 RANLIB="ls -l"
+
+          
