Update apple_m.yml

diff --git a/.github/workflows/apple_m.yml b/.github/workflows/apple_m.yml
--- a/.github/workflows/apple_m.yml
+++ b/.github/workflows/apple_m.yml
@@ -156,8 +156,7 @@ jobs:
               ;;
           esac
 
-          
-  xbuild:
+  xbuild-x86_64:
     runs-on: macos-26
 
     strategy:
@@ -190,7 +189,7 @@ jobs:
             exit 1
           fi
           
-      - name: Crossbuild OpenBLAS
+      - name: Crossbuild OpenBLAS to x86_64
         run: |
           #export PATH=/opt/homebrew/opt/llvm/bin:$PATH
           #export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
@@ -208,4 +207,49 @@ jobs:
           export CFLAGS="-O2 -unwindlib=none -Wno-macro-redefined -isysroot /Applications/Xcode_26.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.0.sdk -arch x86_64"
           make TARGET=CORE2 DYNAMIC_ARCH=1 NUM_THREADS=32 HOSTCC=clang NOFORTRAN=1 RANLIB="ls -l"
 
-          
+  xbuild-ios:
+      runs-on: macos-26
+
+    strategy:
+      fail-fast: false
+        
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v6
+
+      - name: Print system information
+        run: |
+          if [ "$RUNNER_OS" == "macOS" ]; then
+            sysctl -a | grep machdep.cpu
+          else
+            echo "::error::$RUNNER_OS not supported"
+            exit 1
+          fi
+
+      - name: Install Dependencies
+        run: |
+          if [ "$RUNNER_OS" == "Linux" ]; then
+            sudo apt-get install -y gfortran cmake ccache libtinfo5
+          elif [ "$RUNNER_OS" == "macOS" ]; then
+            # It looks like "gfortran" isn't working correctly unless "gcc" is re-installed.
+            brew reinstall gcc
+            brew install coreutils ccache
+            brew install llvm
+          else
+            echo "::error::$RUNNER_OS not supported"
+            exit 1
+          fi
+
+      - name: Crossbuild to iOS
+        run: |
+          #brew install llvm
+          #export #PATH=/opt/homebrew/opt/llvm/bin:$PATH
+          # export #LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
+          export #CPPFLAGS="-I/opt/homebrew/opt/llvm/include" 
+          export CC=/Applications/Xcode_26.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
+          export CFLAGS="-O2 -unwindlib=none -Wno-macro-redefined -isysroot /Applications/Xcode_26.0.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS26.0.sdk -arch arm64 -miphoneos-version-min=10.0"
+          xcrun --sdk iphoneos --show-sdk-path
+          ls -l /Applications
+          make TARGET=ARMV8 NUM_THREADS=32 HOSTCC=clang NOFORTRAN=1 CROSS=1
+
+  
